// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace EXE201_2RE_API.Models;

public partial class TblOrderHistory
{
    [Key]
    public Guid? orderHistoryId { get; set; }

    public Guid? cartId { get; set; }

    public string? status { get; set; }

    public DateTime? changedAt { get; set; }

    public virtual TblCart? cart { get; set; }
}