// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace EXE201_2RE_API.Models;

public partial class TblProduct
{
    [Key]
    public Guid productId { get; set; }

    public Guid? shopOwnerId { get; set; }

    public Guid? categoryId { get; set; }

    public Guid? genderCategoryId { get; set; }

    public Guid? sizeId { get; set; }

    public string? name { get; set; }

    public decimal? price { get; set; }

    public decimal? sale { get; set; }

    public string? description { get; set; }

    public string? brand { get; set; }

    public string? condition { get; set; }

    public string? status { get; set; }

    public DateTime? createdAt { get; set; }

    public DateTime? updatedAt { get; set; }

    public virtual TblCategory? category { get; set; }

    public virtual TblGenderCategory? genderCategory { get; set; }

    public virtual TblUser? shopOwner { get; set; }

    public virtual TblSize? size { get; set; }

    public virtual ICollection<TblCartDetail>? tblCartDetails { get; set; } = new List<TblCartDetail>();
    public virtual ICollection<TblProductImage>? tblProductImages { get; set; } = new List<TblProductImage>();
    public virtual ICollection<TblReview>? tblReviews { get; set; } = new List<TblReview>();
    public virtual ICollection<TblFavorite>? tblFavorites { get; set; } = new List<TblFavorite>();

}