// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace EXE201_2RE_API.Models;

public partial class TblTransaction
{
    [Key]
    public Guid? transactionId { get; set; }
    public Guid? userId { get; set; }
    public decimal? totalMoney { get; set; }
    public int? month { get; set; }
    public int? year { get; set; }
    public string? status { get; set; }
    public virtual TblUser? user { get; set; }
}
