// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace EXE201_2RE_API.Models;

public partial class TblCartDetail
{
    [Key]
    public Guid? cartDetailId { get; set; }

    public Guid? cartId { get; set; }

    public Guid? productId { get; set; }

    public decimal? price { get; set; }

    public virtual TblCart? cart { get; set; }

    public virtual TblProduct? product { get; set; }
}