// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace EXE201_2RE_API.Models;

public partial class TblReview
{
    [Key]
    public Guid reviewId { get; set; }

    public Guid? userId { get; set; }

    public Guid? shopId { get; set; }

    public int? rating { get; set; }

    public string? comment { get; set; }

    public DateTime? createdAt { get; set; }
    public virtual TblUser? user { get; set; }
    public virtual TblUser? shop { get; set; }

}